import {
    PreparedRoll,
    RollType,
    SkillRoll
} from "../dice/RollTypes.js";


const ENRICHER_SELECTOR = "[data-sr6-enricher-action]";
const LOG_PREFIX = "SR6E | Enricher";

/**
 * Handle delegated click events generated by SR6 text enrichers.
 *
 * @param {MouseEvent} event
 * @returns {Promise<void>}
 */
export async function onSR6EnricherClick(event) {
    const eventTarget = event.target;

    // A click target is not always an Element.
    if (!(eventTarget instanceof Element)) return;

    const enricherElement = eventTarget.closest(ENRICHER_SELECTOR);
    if (!(enricherElement instanceof HTMLElement)) return;

    const action = enricherElement.dataset.sr6EnricherAction;
    if (!action) return;

    try {
        switch (action) {
            case "roll":
                event.preventDefault();
                await handleRollAction(enricherElement);
                break;

            default:
                console.warn(
                    `${LOG_PREFIX} | Unsupported action "${action}"`
                );
        }
    } catch (error) {
        console.error(
            `${LOG_PREFIX} | Failed to handle action "${action}"`,
            error
        );
    }
}

/**
 * Handle an SR6 roll generated by a text enricher.
 *
 * @param {HTMLElement} element
 * @returns {Promise<void>}
 */
async function handleRollAction(element) {
    const rollType = element.dataset.rollType;
    const rollTarget = element.dataset.rollTarget;

    if (!rollType || !rollTarget) {
        console.warn(
            `${LOG_PREFIX} | Invalid enricher roll data`,
            element.dataset
        );
        return;
    }

    switch (rollType) {
        case "Skill": {
            const actors = resolveRollActors();
            if (!actors.length) return;

            for (const actor of actors) {
                await handleSkillRoll(actor, rollTarget);
            }

            break;
        }

        case "Attribute": {
            const actors = resolveRollActors();
            if (!actors.length) return;

            for (const actor of actors) {
                await handleAttributeRoll(actor, rollTarget);
            }

            break;
        }

        default:
            console.warn(
                `${LOG_PREFIX} | Unsupported enricher roll type: ${rollType}`
            );
    }
}

/**
 * Resolve the Actors that should perform an enricher action.
 *
 * Controlled tokens take precedence over the User's assigned character.
 *
 * @returns {Actor[]}
 */
function resolveRollActors() {
    const controlledTokens = canvas.tokens?.controlled ?? [];

    if (controlledTokens.length) {
        const actors = controlledTokens
            .map(token => token.actor)
            .filter(actor => actor?.isOwner);

        if (!actors.length) {
            ui.notifications.warn(
                "shadowrun6.ui.notifications.You_are_not_owner_of_the_tokens",
                { localize: true }
            );

            return [];
        }

        return Array.from(
            new Map(
                actors.map(actor => [actor.uuid, actor])
            ).values()
        );
    }

    const character = game.user.character;

    if (character?.isOwner) {
        return [character];
    }

    ui.notifications.warn(
        "shadowrun6.ui.notifications.No_actor_or_tokens_selected",
        { localize: true }
    );

    return [];
}


/**
 * Execute a Skill roll for an Actor.
 *
 * @param {Actor} actor
 * @param {string} skillId
 * @returns {Promise<*>}
 */
async function handleSkillRoll(actor, skillId) {
    const skillDefinition = CONFIG.SR6.ATTRIB_BY_SKILL.get(skillId);

    if (!skillDefinition) {
        console.warn(
            `${LOG_PREFIX} | Unsupported skill ID "${skillId}"`
        );
        return;
    }

    const actorSkill = actor.system.skills?.[skillId];

    if (!actorSkill) {
        console.warn(
            `${LOG_PREFIX} | Actor "${actor.name}" has no data for skill "${skillId}"`
        );
        return;
    }

    const roll = new SkillRoll(actor.system, skillId);

    return actor.rollSkill(roll);
}

/**
 * Execute an Attribute roll for an Actor.
 *
 * @param {Actor} actor
 * @param {string} attributeId
 * @returns {Promise<*>}
 */
async function handleAttributeRoll(actor, attributeId) {
    if (!CONFIG.SR6.ATTRIBUTES.includes(attributeId)) {
        console.warn(
            `${LOG_PREFIX} | Unsupported attribute "${attributeId}"`
        );
        return;
    }

    const attribute = actor.system.attributes?.[attributeId];
    const pool = Number(attribute?.pool);

    if (!Number.isFinite(pool)) {
        console.warn(
            `${LOG_PREFIX} | Actor "${actor.name}" does not have attribute "${attributeId}"`
        );
        return;
    }

    const roll = new PreparedRoll();

    roll.pool = pool;
    roll.rollType = RollType.Common;
    roll.actionText = game.i18n.localize(`attrib.${attributeId}`);
    roll.checkText = roll.actionText;

    roll.allowBuyHits = true;
    roll.useAttributeMod = true;
    roll.attributeTested = attributeId;

    const dialogConfig = {
        useModifier: true,
        useThreshold: true
    };

    return actor.rollCommonCheck(roll, dialogConfig);
}